mongo:
  image: mongo
  environment:
    MONGO_INITDB_ROOT_USERNAME: petshop
    MONGO_INITDB_ROOT_PASSWORD: petshopdb
  ports:
    - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"